Sub FormatEmployeeReport()

    Dim ws As Worksheet
    Dim lastRow As Long
    Dim i As Long
    
    ' ============================================================
    ' SHEET 1: Report
    ' ============================================================
    Set ws = ThisWorkbook.Sheets("Report")
    lastRow = ws.Cells(ws.Rows.Count, "A").End(xlUp).Row
    
    ' Insert 3 rows at top for title, subtitle, spacer
    ws.Rows("1:3").Insert Shift:=xlDown
    
    ' Row 1: Title bar
    ws.Range("A1:F1").Merge
    ws.Range("A1").Value = "EMPLOYEE REPORT"
    ws.Range("A1:F1").Interior.Color = RGB(13, 79, 79)
    ws.Range("A1").Font.Color = RGB(255, 255, 255)
    ws.Range("A1").Font.Size = 14
    ws.Range("A1").Font.Bold = True
    ws.Range("A1").Font.Name = "Calibri"
    ws.Range("A1").HorizontalAlignment = xlCenter
    ws.Range("A1").VerticalAlignment = xlCenter
    ws.Rows(1).RowHeight = 38
    
    ' Row 2: Subtitle
    ws.Range("A2:F2").Merge
    ws.Range("A2").Value = "Generated by UiPath Bot  |  " & Format(Now, "dd-MMM-yyyy HH:mm")
    ws.Range("A2").Font.Color = RGB(136, 136, 136)
    ws.Range("A2").Font.Size = 10
    ws.Range("A2").Font.Italic = True
    ws.Range("A2").Font.Name = "Calibri"
    ws.Range("A2").HorizontalAlignment = xlCenter
    
    ' Row 3: Spacer
    ws.Rows(3).RowHeight = 6
    
    ' Row 4: Column headers (data headers pushed down by 3 rows)
    lastRow = lastRow + 3
    ws.Range("A4:F4").Interior.Color = RGB(212, 168, 67)
    ws.Range("A4:F4").Font.Bold = True
    ws.Range("A4:F4").Font.Size = 11
    ws.Range("A4:F4").Font.Name = "Calibri"
    ws.Range("A4:F4").Font.Color = RGB(26, 26, 26)
    ws.Range("A4:F4").HorizontalAlignment = xlCenter
    ws.Range("A4:F4").VerticalAlignment = xlCenter
    ws.Rows(4).RowHeight = 28
    
    ' Add borders to header
    Dim headerRange As Range
    Set headerRange = ws.Range("A4:F4")
    headerRange.Borders.LineStyle = xlContinuous
    headerRange.Borders.Color = RGB(204, 204, 204)
    
    ' Data rows: alternating colors + borders
    For i = 5 To lastRow
        Dim dataRange As Range
        Set dataRange = ws.Range("A" & i & ":F" & i)
        
        ' Alternating colors
        If (i - 5) Mod 2 = 0 Then
            dataRange.Interior.Color = RGB(224, 242, 241)
        Else
            dataRange.Interior.Color = RGB(255, 255, 255)
        End If
        
        ' Font
        dataRange.Font.Name = "Calibri"
        dataRange.Font.Size = 11
        
        ' Borders
        dataRange.Borders.LineStyle = xlContinuous
        dataRange.Borders.Color = RGB(204, 204, 204)
        
        ' Center align columns A, C, D, F
        ws.Range("A" & i).HorizontalAlignment = xlCenter
        ws.Range("C" & i).HorizontalAlignment = xlCenter
        ws.Range("D" & i).HorizontalAlignment = xlCenter
        ws.Range("F" & i).HorizontalAlignment = xlCenter
        
        ' Right align salary column E
        ws.Range("E" & i).HorizontalAlignment = xlRight
        ws.Range("E" & i).NumberFormat = "#,##0"
        
        ' Color code Category column F
        If ws.Range("F" & i).Value = "High Earner" Then
            ws.Range("F" & i).Font.Color = RGB(46, 125, 50)
            ws.Range("F" & i).Font.Bold = True
        Else
            ws.Range("F" & i).Font.Color = RGB(85, 85, 85)
        End If
    Next i
    
    ' Column widths
    ws.Columns("A").ColumnWidth = 12
    ws.Columns("B").ColumnWidth = 22
    ws.Columns("C").ColumnWidth = 16
    ws.Columns("D").ColumnWidth = 14
    ws.Columns("E").ColumnWidth = 14
    ws.Columns("F").ColumnWidth = 16
    
    ' ============================================================
    ' SHEET 2: Summary
    ' ============================================================
    Set ws = ThisWorkbook.Sheets("Summary")
    lastRow = ws.Cells(ws.Rows.Count, "A").End(xlUp).Row
    
    ' Insert 3 rows at top
    ws.Rows("1:3").Insert Shift:=xlDown
    
    ' Row 1: Title bar
    ws.Range("A1:B1").Merge
    ws.Range("A1").Value = "REPORT SUMMARY"
    ws.Range("A1:B1").Interior.Color = RGB(13, 79, 79)
    ws.Range("A1").Font.Color = RGB(255, 255, 255)
    ws.Range("A1").Font.Size = 14
    ws.Range("A1").Font.Bold = True
    ws.Range("A1").Font.Name = "Calibri"
    ws.Range("A1").HorizontalAlignment = xlCenter
    ws.Range("A1").VerticalAlignment = xlCenter
    ws.Rows(1).RowHeight = 38
    
    ' Row 2: Subtitle
    ws.Range("A2:B2").Merge
    ws.Range("A2").Value = "Auto-generated metrics"
    ws.Range("A2").Font.Color = RGB(136, 136, 136)
    ws.Range("A2").Font.Size = 10
    ws.Range("A2").Font.Italic = True
    ws.Range("A2").Font.Name = "Calibri"
    ws.Range("A2").HorizontalAlignment = xlCenter
    
    ' Row 3: Spacer
    ws.Rows(3).RowHeight = 6
    
    ' Row 4: Column headers (pushed down by 3)
    lastRow = lastRow + 3
    ws.Range("A4:B4").Interior.Color = RGB(212, 168, 67)
    ws.Range("A4:B4").Font.Bold = True
    ws.Range("A4:B4").Font.Size = 11
    ws.Range("A4:B4").Font.Name = "Calibri"
    ws.Range("A4:B4").Font.Color = RGB(26, 26, 26)
    ws.Range("A4:B4").HorizontalAlignment = xlCenter
    ws.Rows(4).RowHeight = 28
    ws.Range("A4:B4").Borders.LineStyle = xlContinuous
    ws.Range("A4:B4").Borders.Color = RGB(204, 204, 204)
    
    ' Data rows
    For i = 5 To lastRow
        Dim sumRange As Range
        Set sumRange = ws.Range("A" & i & ":B" & i)
        
        ' Alternating colors
        If (i - 5) Mod 2 = 0 Then
            sumRange.Interior.Color = RGB(224, 242, 241)
        Else
            sumRange.Interior.Color = RGB(255, 255, 255)
        End If
        
        ' Font
        sumRange.Font.Name = "Calibri"
        sumRange.Font.Size = 11
        ws.Range("A" & i).Font.Bold = True
        
        ' Borders
        sumRange.Borders.LineStyle = xlContinuous
        sumRange.Borders.Color = RGB(204, 204, 204)
    Next i
    
    ' Column widths
    ws.Columns("A").ColumnWidth = 22
    ws.Columns("B").ColumnWidth = 28

End Sub